#include <stdio.h>
#include <stdlib.h>
#include <time.h>
/* more headers goes there */
/**
* main -prints random number generated by program
 *
 * Description: prints positive if > 0 , if < 0 negative,or zero if == 0
 * Return: 0 if succesfull
 */
/* betty style doc for function main goes there */
int main(void)
{
	int n;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	if (n > 0)
	{
		printf("%d is positive\n", n);
	}
	else if (n == 0)
	{
		printf("%d is 0\n", n);
	}
	else if (n < 0)
	{
		printf("%d is negative\n", n);
	}
	/* your code goes there */
	return (0);
}
